# Generated by Django 5.2.3 on 2025-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
